import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowDown, ArrowRight, ArrowUpRight, Award, ChevronDown, ExternalLink, Leaf, Menu, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import { activities, latest, metrics, openResearch, projects, sources, years, type Verification } from './data'
import './style.css'

const statusText: Record<Verification, string> = { verified: 'Source confirmée', partial: 'À confirmer', pending: 'En recherche' }
function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [year, setYear] = useState('Toutes les années')
  const [query, setQuery] = useState('')
  const [projectTheme, setProjectTheme] = useState('Tous les thèmes')
  const projectThemes = [...new Set(projects.map((p) => p.theme))]
  const visibleProjects = projects.filter((p) => (year === 'Toutes les années' || p.year === year) && (projectTheme === 'Tous les thèmes' || p.theme === projectTheme))
  const filtered = useMemo(() => activities.filter((a) => (year === 'Toutes les années' || a.year === year) && `${a.title} ${a.summary} ${a.kind}`.toLowerCase().includes(query.toLowerCase())), [year, query])
  const closeMenu = () => setMenuOpen(false)
  return <>
    <a className="skip" href="#contenu">Aller au contenu</a>
    <header className="header"><a className="brand" href="#accueil" aria-label="Enactus FPL Larache, accueil"><span className="brand-mark">E<span>•</span></span><span>ENACTUS <small>FPL LARACHE</small></span></a><button className="menu-toggle" aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'nav nav-open' : 'nav'} aria-label="Navigation principale">{[['Notre histoire','#histoire'],['Projets','#projets'],['Archives','#archives'],['Impact','#impact'],['Actualités','#actualites']].map(([label,href])=><a key={href} onClick={closeMenu} href={href}>{label}</a>)}<a className="nav-cta" onClick={closeMenu} href="#contact">Nous rejoindre <ArrowUpRight size={15}/></a></nav></header>
    <main id="contenu">
      <section className="hero" id="accueil"><div className="hero-grid"/><div className="hero-copy"><p className="eyebrow"><span className="pulse"/> ENTREPRENDRE POUR DEMAIN <span className="eyebrow-place">· LARACHE, MAROC</span></p><h1>Des idées<br/>en <em>action.</em><br/>Un impact<br/>qui <em>compte.</em></h1><p className="hero-sub">Nous faisons de l’entrepreneuriat étudiant un levier d’action pour notre territoire.</p><div className="hero-actions"><a className="button button-gold" href="#projets">Explorer nos projets <ArrowRight size={17}/></a><a className="text-link" href="#histoire">Découvrir notre histoire <ArrowDown size={15}/></a></div><div className="hero-note"><span className="note-line"/> Une équipe étudiante · Faculté Polydisciplinaire de Larache</div></div><div className="hero-art" aria-label="Illustration abstraite évoquant les collines du nord du Maroc"><div className="sun"/><div className="hill hill-back"/><div className="hill hill-mid"/><div className="hill hill-front"/><div className="art-stamp">IMAGINER<br/>ENSEMBLE<br/><b>✳</b></div><div className="art-label">34° 41′ N&nbsp; 6° 12′ W <span>MAROC · ATLANTIQUE</span></div></div><div className="hero-rail">01 <span/> 05</div><span className="hero-vertical">L’AVENIR PREND RACINE ICI</span></section>
      <section className="intro section" id="histoire"><div className="section-kicker">01 — NOTRE HISTOIRE</div><div className="intro-main"><h2>Le changement<br/>commence <em>près de chez soi.</em></h2><div className="intro-body"><p>Enactus FPL Larache réunit des étudiant·es qui explorent l’entrepreneuriat comme une façon concrète de répondre aux défis sociaux, économiques et environnementaux.</p><p>Notre archive raconte ce que les sources permettent d’établir aujourd’hui — et rend visibles les histoires qu’il reste à documenter.</p><a className="inline-link" href="https://fpl.ac.ma/" target="_blank" rel="noreferrer">Faculté Polydisciplinaire de Larache <ArrowUpRight size={15}/></a></div></div><div className="values"><div><span>01</span><h3>Écouter</h3><p>Comprendre les réalités du territoire avant de proposer une solution.</p></div><div><span>02</span><h3>Expérimenter</h3><p>Faire évoluer des idées par l’apprentissage, le terrain et le dialogue.</p></div><div><span>03</span><h3>Transmettre</h3><p>Garder une mémoire utile et accessible aux équipes qui suivent.</p></div></div></section>
      <section className="projects-section section" id="projets"><div className="section-head"><div><div className="section-kicker">02 — PROJETS DOCUMENTÉS</div><h2>Des idées ancrées<br/>dans le <em>réel.</em></h2></div><a className="inline-link" href="#archives">Voir toutes les archives <ArrowRight size={16}/></a></div><div className="project-filters"><label>Année<select value={year} onChange={e=>setYear(e.target.value)}><option>Toutes les années</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Thème<select value={projectTheme} onChange={e=>setProjectTheme(e.target.value)}><option>Tous les thèmes</option>{projectThemes.map(t=><option key={t}>{t}</option>)}</select></label><span>{visibleProjects.length} projet{visibleProjects.length!==1?'s':''} documenté{visibleProjects.length!==1?'s':''}</span></div><div className="project-grid">{visibleProjects.map((p,i)=><article className={`project-card project-${projects.findIndex(item=>item.id===p.id)+1}`} key={p.id}><div className="project-visual"><div className={p.id==='tijwal'?'visual-map':'visual-salt'} aria-hidden="true">{p.id==='tijwal'?<><span className="map-route"/><span className="map-point p1"/><span className="map-point p2"/><span className="map-word">TIJWAL</span><span className="map-coord">NORD DU MAROC<br/>TERRITOIRES À DÉCOUVRIR</span></>:<><span className="salt-orb orb-a"/><span className="salt-orb orb-b"/><span className="salt-orb orb-c"/><span className="salt-title">SEL<br/>&amp; SAVOIR-FAIRE</span><span className="salt-foot">VALORISATION LOCALE · 2025</span></>}</div><span className="project-count">0{i+1} / 0{visibleProjects.length}</span></div><div className="project-info"><div className="project-tags"><span>{p.theme}</span><span>{p.year}</span></div><h3>{p.name}</h3><p>{p.summary}</p><span className={`status status-${p.status}`}><i/>{statusText[p.status]}</span><details className="project-details"><summary>Lire la fiche <ChevronDown size={15}/></summary><div className="detail-content"><p>{p.detail}</p><p><b>Étape documentée :</b> {p.stage}</p>{p.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">Source : {s.title} <ExternalLink size={13}/></a>)}</div></details></div></article>)}</div>{visibleProjects.length===0&&<p className="no-results">Aucun projet sourcé pour ces filtres.</p>}<div className="archive-note"><ShieldCheck size={19}/><p><b>Transparence avant tout.</b> Les sources disponibles ne confirment pas encore de chiffres d’impact propres à l’équipe. Les données provisoires sont identifiées et reliées à leur origine.</p></div></section>
      <section className="impact section" id="impact"><div className="impact-orbit" aria-hidden="true"><div className="orbit-ring ring1"/><div className="orbit-ring ring2"/><div className="orbit-core"><Leaf size={32}/><span>MESURER<br/>AVEC SOIN</span></div><span className="orbit-dot dot1"/><span className="orbit-dot dot2"/><span className="orbit-dot dot3"/></div><div className="impact-copy"><div className="section-kicker">03 — IMPACT</div><h2>La preuve<br/>avant le <em>chiffre.</em></h2><p>Une mesure utile doit avoir une définition, une période et une source. Nous n’avons pas encore trouvé d’indicateurs d’impact de l’équipe suffisamment documentés pour les publier comme résultats vérifiés.</p><div className="empty-impact"><span className="empty-icon"><Sparkles size={18}/></span><div><b>Les indicateurs arrivent avec les preuves.</b><small>La collecte de données est en cours.</small></div></div><a className="inline-link" href={sources.mwn.url} target="_blank" rel="noreferrer">Consulter les résultats rapportés au SIF 2025 <ArrowUpRight size={15}/></a></div></section>
      <section className="archive section" id="archives"><div className="archive-header"><div><div className="section-kicker">04 — CINQ ANNÉES D’ARCHIVES</div><h2>Une histoire en<br/><em>construction.</em></h2></div><p>Un registre vivant. Chaque entrée indique ce qui est établi, ce qui reste à vérifier et d’où vient l’information.</p></div><div className="year-strip">{years.map((y,i)=><button className={year===y?'year-chip active':''} key={y} onClick={()=>setYear(year===y?'Toutes les années':y)}><small>0{i+1}</small>{y}</button>)}</div><div className="archive-tools"><label className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une activité…" aria-label="Rechercher dans les archives"/>{query&&<button aria-label="Effacer la recherche" onClick={()=>setQuery('')}><X size={15}/></button>}</label><span className="result-count">{filtered.length} entrée{filtered.length!==1?'s':''} sourcée{filtered.length!==1?'s':''}</span></div><div className="timeline">{filtered.length ? filtered.map(a=><article className="timeline-item" key={a.id}><div className="timeline-date"><b>{new Date(`${a.date}T12:00:00`).toLocaleDateString('fr-FR',{day:'2-digit',month:'short'})}</b><span>{a.year}</span></div><span className="timeline-dot"/><div className="timeline-content"><div className="timeline-meta"><span>{a.kind}</span><span className={`status status-${a.status}`}><i/>{statusText[a.status]}</span></div><h3>{a.title}</h3><p>{a.summary}</p><p className="place">⌖ &nbsp;{a.location}</p><details><summary>Vérification &amp; source <ChevronDown size={14}/></summary><div className="detail-content"><p>{a.note}</p>{a.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} <ExternalLink size={13}/></a>)}</div></details></div></article>) : <div className="no-results">Aucune entrée pour cette recherche. Essayez d’autres mots ou une autre année.</div>}</div><div className="research-gaps"><h3>Les années à documenter</h3><div className="gaps-grid">{years.map(y=><div key={y}><span>{y}</span><p>{openResearch[y]}</p></div>)}</div><p className="gap-footnote">La mention du centre Innovation Enactus FPL en mars 2024 provient d’un récit d’événement de RADEEL ; elle n’est pas comptée ici comme activité portée par l’équipe. <a href={sources.radeel.url} target="_blank" rel="noreferrer">Voir la source <ArrowUpRight size={12}/></a></p></div></section>
      <section className="latest section" id="actualites"><div className="section-head"><div><div className="section-kicker">05 — AU FIL DE L’ACTUALITÉ</div><h2>Les nouvelles<br/><em>du collectif.</em></h2></div><span className="latest-separate"><Award size={16}/> Hors archive historique</span></div><div className="news-grid">{latest.map((n,i)=><article className="news-card" key={n.title}><div className="news-top"><span>ACTUALITÉ · 2026</span><span>0{i+1}</span></div><span className="news-symbol">{i===0?<Award size={30}/>:<Sparkles size={30}/>}</span><time>{n.date}</time><h3>{n.title}</h3><p>{n.summary}</p><a href={n.source.url} target="_blank" rel="noreferrer">Lire la source <ArrowUpRight size={14}/></a></article>)}</div></section>
      <section className="join" id="contact"><div className="join-bg">ENACTUS</div><div className="join-content"><div className="section-kicker">LA SUITE S’ÉCRIT ENSEMBLE</div><h2>Votre histoire<br/>fait partie de <em>la nôtre.</em></h2><p>Vous avez participé à un projet, accompagné l’équipe ou conservé des archives ? Aidez-nous à rendre cette mémoire plus complète et plus juste.</p><div className="join-actions"><a className="button button-gold" href="https://www.linkedin.com/company/enactus-fplarache/" target="_blank" rel="noreferrer">Contacter l’équipe <ArrowUpRight size={16}/></a><a className="join-fpl" href="https://fpl.ac.ma/" target="_blank" rel="noreferrer">Partenaire institutionnel : FPL <ArrowUpRight size={14}/></a></div></div></section>
    </main><footer className="footer"><a className="brand brand-footer" href="#accueil"><span className="brand-mark">E<span>•</span></span><span>ENACTUS <small>FPL LARACHE</small></span></a><p>Des idées en action. Une mémoire ouverte.</p><div className="footer-right"><span>Sources vérifiées · Mise à jour 2026</span><a href="#accueil">Retour en haut ↑</a></div></footer>
    <div className="mobile-bottom"><a href="#contact">Contribuer à l’archive <ArrowUpRight size={15}/></a></div>
    <div className="sr-only">{metrics.length} indicateur vérifié disponible.</div>
  </>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
